mds.repository=C:/JDeveloper/soamds
oracle.home=C:/Oracle/Middleware/Oracle_Home

serverURL=http://localhost:70034
user=weblogic1
password=redhat@12345

overwrite=true

revision=1.0
mds.deploy.dir=D:/jdeveloper_git/git/mds_deployment/mds_deploy