mds.repository=C:/JDeveloper/soamds
oracle.home=C:/Oracle/Middleware/Oracle_Home
deploy.serverURL=http://localhost:7001
deploy.user=weblogic
deploy.password=redhat@123
overwrite=true
compositeDir=D:/jdeveloper_git/git/mds_deployment/SOA
revision=1.0